use_small_heuristics = "Max"
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
brace_style = "PreferSameLine"
fn_single_line = true
where_single_line = true
force_explicit_abi = true
format_strings = true
format_macro_matchers = true
imports_indent = "Visual"
merge_imports = true
match_block_trailing_comma = true
max_width = 120
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
overflow_delimited_expr = true
edition = "2018"
version = "Two"
normalize_doc_attributes = true